I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 622, in script call
    call cliff_party
  File "game/script.rpy", line 1647, in script
    show cl sneercos with moveinright:
TypeError: got an unexpected keyword argument 'old_widget'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 622, in script call
    call cliff_party
  File "game/script.rpy", line 1647, in script
    show cl sneercos with moveinright:
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1367, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\exports\statementexports.py", line 257, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 1578, in do_with
    return self.interact(trans_pause=True,
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2666, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\display\core.py", line 2575, in instantiate_transition
    trans = self.ongoing_transition[layer](
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\atl.py", line 623, in __call__
    new_scope = signature.apply(args, kwargs, partial=True, apply_defaults=False)
  File "c:\Users\toast\Downloads\renpy-8.3.4-sdk\renpy\parameter.py", line 384, in apply
    raise TypeError(
TypeError: got an unexpected keyword argument 'old_widget'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Still Heart 1.0
Mon Sep 29 12:15:55 2025
